version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: rs-api
    ports:
      - 8887:80
    environment:
      - MAX_WORKERS=4
      - TIMEOUT=300
    volumes:
      - ./:/app
