version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: rs-api-$NAME
    ports:
      - $API_PORT:80
    environment:
      - MAX_WORKERS=4
      - TIMEOUT=3000
    volumes:
      - ./:/app
