version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: rs-api-$NAME
    ports:
      - $API_PORT:80
    environment:
      - MAX_WORKERS=4
      - TIMEOUT=3000
    volumes:
      - ./:/app

  filebeat:
    image: docker.elastic.co/beats/filebeat:${ES_VERSION}
    user: root
    container_name: rs-filebeat-$NAME
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:rw
      - ./logs/elasticsearch.log:/usr/share/logs/elasticsearch.log
    
