name: researcher-searcher-api
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.9
  - black=19.10b0
  - neo4j-python-driver=4.1
  - pandas=1.1.3
  - environs=8.0.0
  - loguru=0.5.3
  - pip=20.2.4
  - elasticsearch
  - scikit-learn
  - altair
  - plotly=4.14.3
  - fastapi
  - uvicorn  
  - pip:
    - certifi==2021.5.30        
    - simple-parsing
    - spacy
    - scispacy
    - pytest
    - spacy-universal-sentence-encoder
    - anonymizeip

